import { chromium } from 'playwright';
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage();
page.on('console', m => console.log('console', m.type(), m.text()));
page.on('pageerror', e => console.log('pageerror', e.message));
await page.goto('http://localhost:4200/', { waitUntil: 'networkidle' });
console.log('url', page.url());
console.log('bodyText', (await page.locator('body').innerText()).slice(0, 1500));
console.log('h1count', await page.locator('h1').count());
if (await page.locator('h1').count()) console.log('h1', await page.locator('h1').first().innerText());
await page.screenshot({ path: '/tmp/login-check.png', fullPage: true });
await browser.close();
